### ISSUE TITLE
root access to docker

### ISSUE THREAD

**Issue by collazosc** [jbossdemocentral/bpms-travel-agency-demo#12]
Is it possible to have the password for root access to docker? Would like to install some utilities to see the demo better.

Thanks in advance,

Carlos Collazos

**Comment by sabre1041** [comment]
PR submitted to provide root access for jboss user 

https://github.com/jbossdemocentral/docker-developer/pull/3

**Comment by eschabell** [comment]
Merged into docker-developer, fixes #12.
