### ISSUE TITLE
Installer fails with maven compiler annotations not supported

### ISSUE THREAD

**Issue by joel-dixon** [jbossdemocentral/bpms-travel-agency-demo#27]
While attempting to run the installation process, I got errors for the maven build of the projects.  The errors included text like "annotations are not supported in -source 1.3".  To work around this issue, I needed to edit the pom.xml files for projects (including acme-demo-hotel-service, acme-demo-flight-service, and acme-data-mode) to tell the maven compiler plugin to force usage of Java 1.6.  The edits include a section like this:
```
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

This error occurred on Ubuntu 14.04 LTS, Maven 3.0.5

**Comment by eschabell** [comment]
Can you pull the lastest master as two 6.2 product updates crept into that branch (might be what you are hitting?) and were just now rolled back.

Verify that it is still in there and I will follow up.

**Comment by joel-dixon** [comment]
I just did a clone and got the exact same error.  Here's the commit ID that I'm at when I cloned master.
commit 630f47717a2797dd65af4bcc34828a673c73f987

**Comment by eschabell** [comment]
Aaah, looking closer at this, the expected java versions needs to be 7 or 8. JBoss BPM Suite does not support java 6 in the latest versions.

If you want to use something with Java 6 then grab a tag version that is older, see github project for tags available (in released versions section).

**Comment by joel-dixon** [comment]
I should have been clearer by saying "at least version 6".  Actually, I'm using Java 8:
Here's my output from "mvn -v"
'''
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-25-generic", arch: "amd64", family: "unix"
'''

Many others online mention that Maven will default to compile for Java release 3 for some reason, and that you may need to force it with the pom.xml tags mentioned above.

Looking here:
https://maven.apache.org/plugins/maven-compiler-plugin/

They seem to infer that it will default to source revision "1.5".  They mention that they are passing the above source version specification as a "-source <release>" command-line option to the javac compiler.  (see here https://maven.apache.org/plugins/maven-compiler-plugin/ )

So, to ensure that it _compiles_ with release spec 1.6, the tags in the pom file may be required.

**Comment by eschabell** [comment]
This makes more sense now... what I have done is add your build section to the main root pom in the projects directory, but in the 6.2 branch and will pull that into master when we get the issues around new product ironed out.

Sound good?

**Comment by joel-dixon** [comment]
I tried the updated branch 6.2 and can see the updated projects/pom.xml, but I still get the same error.  If I copy your new "build" section from the projects/pom.xml, and copy it to the projects/acme-demo-flight-service/pom.xml, then that sub project is able to build.  I'm not familiar enough with Maven to know about project hierarchy inheritance.
