### ISSUE TITLE
External client references wrong deployment-unit

### ISSUE THREAD

**Issue by DuncanDoyle** [jbossdemocentral/bpms-travel-agency-demo#37]
The external client UI references the 2.0.0 version of the Travel Agency deployment unit. However, we've recently upgraded the project to version 2.0.1, which causes the client RESTful requests to fail.

**Comment by sabre1041** [comment]
@DuncanDoyle not sure the error you are seeing (401?), but newer versions of the product require the user have `rest-all` or similar permissions

**Comment by DuncanDoyle** [comment]
That's not the problem. It's a 404, already fixed it. Will push change in the next 10 minutes.
