### ISSUE TITLE
Problems while building

### ISSUE THREAD

**Issue by razielangelo** [jbossdemocentral/bpms-travel-agency-demo#47]
Hello team,

I have a developer red hat account, because of that I was not able to download the EAP patch 6.4, so i had to install the demo without that patch because is not available for developers.

I am having an issue with the type of data flight, hotelrequest, and hotelws, Log attached.

This only can be solved using the patch of the EAP? is there any other work around tosolve this problem with no customer account?

Thank you, I hope you can help me, I am trying to test the product in order to see capabilities and decide to implement it in my company.

Thanks for your answers.

I amusing BPM 6.3 and EAP 6.0

ERROR [org.drools.compiler.kie.builder.impl.AbstractKieModule](http-/127.0.0.1:8080-7) Unable to build KieBaseModel:defaultKieBase
Unable to generate action invoker. : Process org.specialtripsagency.specialtripsagencyprocess(org.specialtripsagency.specialtripsagencyprocess)
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563Action49Invoker.java (12:396) : com.jboss.soap.service.acmedemo.Flight cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563Action49Invoker.java (12:449) : com.jboss.soap.service.acmedemo.Flight cannot be resolved to a type

Unable to generate action invoker. : Process org.specialtripsagency.specialtripsagencyprocess(org.specialtripsagency.specialtripsagencyprocess)
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563Action53Invoker.java (12:396) : acme.service.soap.hotelws.Resort cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563Action53Invoker.java (12:442) : acme.service.soap.hotelws.Resort cannot be resolved to a type

Process Compilation error : Process org.specialtripsagency.specialtripsagencyprocess(org.specialtripsagency.specialtripsagencyprocess)
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (48:2654) : acme.service.soap.hotelws.HotelRequest cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (48:2707) : acme.service.soap.hotelws.HotelRequest cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (54:2943) : com.jboss.soap.service.acmedemo.FlightRequest cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (54:3006) : com.jboss.soap.service.acmedemo.FlightRequest cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (365:19386) : com.jboss.soap.service.acmedemo.Flight cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (371:19669) : com.jboss.soap.service.acmedemo.Flight cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (389:20547) : acme.service.soap.hotelws.Resort cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (395:20821) : acme.service.soap.hotelws.Resort cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (418:22091) : com.jboss.soap.service.acmedemo.Flight cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (418:22144) : com.jboss.soap.service.acmedemo.Flight cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (419:22218) : acme.service.soap.hotelws.Resort cannot be resolved to a type
    org/specialtripsagency/Process_org$u46$specialtripsagency$u46$specialtripsagencyprocess270071563.java (419:22264) : acme.service.soap.hotelws.Resort cannot be resolved to a type

**Comment by razielangelo** [comment]
Hello Guys,

Still hope you can guide trough this.

I get the correct versions of the EAP, I was able to call Sales team of Redhat and provide me with the EAP patch needed to run this demo, I reinstall everything from scratch, and still have the same result when tried to build and deploy, I receive the same error.

Any comment on why is this happening? how can i solve it?

**Comment by DuncanDoyle** [comment]
Hi,

What system are you running this on? Windows, Mac OS X, Linux? Which version of Java are you using? When does the error occur? During the execution of the "init" script, when you start the BPM Suite server, or when you try to run the process?

**Comment by razielangelo** [comment]
Hello, I install it in Windows, I have Java 8, and the error comes immediately after open the BPM.
I just install everything as indicates the instructions, ANd i let the server start. When I open the BPM, Logged in and go to Authoring Project Tab, Looks like the BPM is already working and indicate me in the messages screen that cannot resolve as a type the Flight object. ALso i tried tu Build and run the project and give that message,

**Comment by DuncanDoyle** [comment]
Can you try the latest version? I've done a major upgrade, which includes an upgrade to BPM Suite 6.4.0.GA, EAP 6.4, new installers, etc.

**Comment by DuncanDoyle** [comment]
I'm gonna close this due to inactivity. Please re-open if this is still an issue.
