### ISSUE TITLE
Main specialtripsagencyprocess incomplete

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/bpms-travel-agency-demo#53]
See attached image after logging in and opening project:

![screen shot 2016-12-06 at 5 23 32 pm](https://cloud.githubusercontent.com/assets/437001/20933645/00b94f6a-bbd9-11e6-82ef-d25377163933.png)

Funny enough, the project builds.... (Firefox browser on OSX, BPM Suite 6.4 on EAP 7).

**Comment by DuncanDoyle** [comment]
It's probably a problem in the "bpmndi" part of the BPMN2 file (which controls the diagram layout), which could be the reason the process builds fine. I.e. the actual end-node is there in the definition, but not in the diagram.

Will fix ASAP.

**Comment by eschabell** [comment]
Used to be able to view source and could search for the problem... but couldn't find that button right away so just raised the issue. Thanks! ;-)

**Comment by DuncanDoyle** [comment]
Problem seems to be a bit bigger. When I remove the sequence flow connector and add a new EndEvent, the process does not work anymore (I get weird 'null' errors when it wants do a WebService call). I need to dive into this a bit more to solve it.

**Comment by DuncanDoyle** [comment]
Interestingly enough, the problem wasn't even recently introduced, this version introduced the problem:

https://github.com/jbossdemocentral/bpms-travel-agency-demo-repo/blob/889cb9ce297cf159b5dd9d6dd107a3fb1234eeb4/specialtripsagencyproject/src/main/resources/specialtripsagencyprocess.bpmn2

Which is a commit from the 28th of April .... (that's also the commit that introduced the gateway ... ).

**Comment by eschabell** [comment]
So why does it break now?

**Comment by DuncanDoyle** [comment]
Because the "CancelEndEvent" is no longer supported in the designer: https://issues.jboss.org/browse/GUVNOR-2627

Fixed by: https://github.com/jbossdemocentral/bpms-travel-agency-demo-repo/commit/e17a7c3fe2ca3cad935b9d1e459da07fd3881bcd

Note that this is fixed in the separate "bpms-travel-agency-demo**-repo**", which is now used by the installer scripts instead of this one: https://github.com/jbossdemocentral/bpms-travel-agency-demo/tree/master/support/bpm-suite-demo-niogit/specialtripsagency.git

I don't really maintain the latter anymore, but can fix it there as well if required.

**Comment by eschabell** [comment]
I am hitting this running the demo as is on master right now.... through the install.sh.

**Comment by DuncanDoyle** [comment]
Did you re-run the "init.sh" script? I just pushed that commit, so it should pick it up. Will check again.

**Comment by eschabell** [comment]
Testing now... sorry, missed that you updated the external repo... ;-)

**Comment by eschabell** [comment]
Display is good now, but submitted from external UI and failed with:

19:02:09,442 INFO  [stdout] (thread-no-0) IOException caught: 
19:02:09,443 ERROR [stderr] (thread-no-0) java.io.FileNotFoundException: /Users/erics/demo-projects/bpmsuite/bpms-travel-agency-demo/target/jboss-eap-7.0/standalone/tmp/vfs/temp/tempe185f22ed3e393d7/content-9952295f0711f2adsuccess_response.html (No such file or directory)
19:02:09,460 ERROR [stderr] (thread-no-0) 	at java.io.FileInputStream.open0(Native Method)
19:02:09,460 ERROR [stderr] (thread-no-0) 	at java.io.FileInputStream.open(FileInputStream.java:195)
19:02:09,460 ERROR [stderr] (thread-no-0) 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
19:02:09,460 ERROR [stderr] (thread-no-0) 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at java.io.FileReader.<init>(FileReader.java:58)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at com.externalui.example.SimpleServlet.getContent(SimpleServlet.java:65)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at com.externalui.example.SimpleServlet.doGet(SimpleServlet.java:55)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
19:02:09,461 ERROR [stderr] (thread-no-0) 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:285)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:264)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:175)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:792)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19:02:09,462 ERROR [stderr] (thread-no-0) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19:02:09,463 ERROR [stderr] (thread-no-0) 	at java.lang.Thread.run(Thread.java:745)

**Comment by DuncanDoyle** [comment]
Fixed: https://github.com/jbossdemocentral/bpms-travel-agency-demo/commit/de77a60bdc40d87b58de5ea13661cc417b644d42

The way that that application sends a response is super nasty (reading the static content of a HTML from the filesystem and manipulating the HTML content while reading the file .....), so should actually be changed with something a bit better written and more modern (AngularJS/Bootstrap/Patternfly). Patched the problem for now, which seems to work.

**Comment by eschabell** [comment]
Tested the update, now WS failing again, see attached server log for details but:

<exception>
16:50:35,213 ERROR [stderr] (thread-no-53)     <status>FAILURE</status>
16:50:35,213 ERROR [stderr] (thread-no-53)     <url>http://localhost:8080/business-central/rest/runtime/org.specialtripsagency:specialtripsagencyproject:2.0.1/process/org.specialtripsagency.specialtripsagencyprocess/start?map_applicantName=eric&amp;map_emailAddress=erics%40me.com&amp;map_numberOfTravelers=2i&amp;map_preferredDateOfArrival=2016-12-20&amp;map_preferredDateOfDeparture=2&amp;map_otherDetails=N%2FA&amp;map_fromDestination=London&amp;map_toDestination=Edinburgh</url>
16:50:35,361 ERROR [stderr] (thread-no-53)     <message>WorkflowRuntimeException thrown with message '[org.specialtripsagency.specialtripsagencyprocess:1 - Prepare Web Service Data:2] -- java.lang.Long cannot be cast to java.lang.String'</message>
16:50:35,362 ERROR [stderr] (thread-no-53)     <stackTrace>org.kie.remote.services.rest.exception.KieRemoteRestOperationException: [org.specialtripsagency.specialtripsagencyprocess:1 - Prepare Web Service Data:2] -- java.lang.Long cannot be cast to java.lang.String
16:50:35,362 ERROR [stderr] (thread-no-53) 	at org.kie.remote.services.rest.exception.KieRemoteRestOperationException.internalServerError(KieRemoteRestOperationException.java:151)
16:50:35,362 ERROR [stderr] (thread-no-53) 	at org.kie.remote.services.cdi.ProcessRequestBean.doKieSessionOperation(ProcessRequestBean.java:305)

[server.log.zip](https://github.com/jbossdemocentral/bpms-travel-agency-demo/files/642599/server.log.zip)

**Comment by DuncanDoyle** [comment]
That's not a failure in the WS, it's a ClassCastException in the "Prepare Web Service Data" script node which builds the web service request: java.lang.Long cannot be cast to java.lang.String

I can reproduce this when I enter a Long (simply a number) in a field in that external UI that actually expects a String. For example, if you enter a number in the "Applicant Name" field or the "Other Details" field. There is no input validation in the UI, and the data is passed into the REST request as is.

Looking at your request, I can see what's causing this. It's the "preferredDateOfDeparture=2" in your request. That's get mapped to a Long, where it expects a String. If you change that into, for example, "2016-12-18", everything should work fine.

Can you double your input and try again. I tested this on a full fresh install, and can't see anything else that's wrong other than the input.

**Comment by eschabell** [comment]
Yep, too many demos I am working on in parallel, got too quick in the data input... thanks, fixed for me!
