### ISSUE TITLE
JdbcSQLException: Table "PROCESSINSTANCELOG" not found; SQL statement

### ISSUE THREAD

**Issue by pbaker01** [jbossdemocentral/bpms-travel-agency-demo#6]
The install looks clean but I'm unable to launch the demo.  The server logs contains several errors about missing table: PROCESSINSTANCELOG.  
Envt: Windows 7 x64

I tried installing on several machines, all receive the same error. 

Am I missing a step?

----
End of Install:
Connected to Management Interface.
#1 /profile=default/subsystem=web/virtual-server=default-host/sso=configuration:add()
#2 /profile=full/subsystem=web/virtual-server=default-host/sso=configuration:add()
#3 /profile=ha/subsystem=web/virtual-server=default-host/sso=configuration:add()
#4 /profile=full-ha/subsystem=web/virtual-server=default-host/sso=configuration:add()
The batch executed successfully
Script S:\JBoss\demos\bpms-travel-agency-demo-master\target\/jboss-eap-6.1/cli-scripts/add-sso-conf-domain.cli ran successfully.
Starting process Shutdown domain (58/60)
Trying to connect to Management Interface...(1/5).
Connected to Management Interface.
{"outcome" => "success"}

The connection to the controller has been closed as the result of the shutdown operation.
(Although the command prompt will wrongly indicate connection until the next line is entered)
Application Server successfully stopped.
Starting process Cleanup (59/60)
Successfully wrote properties to: S:\JBoss\demos\bpms-travel-agency-demo-master\target\jboss-eap-6.1\standalone\configuration\logging.properties
Starting process Clean up (60/60)
[ Processing finished ]
[ Automated installation done ]

Error trying to start server (standalone.bat)

13:14:52,853 ERROR [org.jboss.dashboard.dataset.sql.SQLDataSet] (ServerService Thread Pool -- 68) Error in load() SQLDataset. SQL = select total.processname, ifnull(total.instances,0) total, ifnull(active.instances_act,0) active, ifnull(completed.instances_compl,0) completed, ifnull(pending.instances_pend,0) pending, ifnull(suspended.instances_susp,0) suspended, ifnull(aborted.instances_abrt,0) aborted
                from
                (select pi.processinstanceid as pId, pi.processname as processname, count(*) as instances

                from processinstancelog pi group by pi.processinstanceid,processname) as total
                left outer join
                (select pi.processinstanceid as pId, count(*) as instances_act
                from processinstancelog pi
                where pi.status=1 group by pi.processinstanceid) as active
                on (total.pId=active.pId)
                left outer join
                (select pi.processinstanceid as pId, count(*) as instances_compl
                from processinstancelog pi
                where pi.status=2 group by pi.processinstanceid) as completed
                on (total.pId=completed.pId)
                left outer join
                (select pi.processinstanceid as pId, count(*) as instances_pend
                from processinstancelog pi
                where pi.status=0 group by pi.processinstanceid) as pending
                on (total.pId=pending.pId)
                left outer join
                (select pi.processinstanceid as pId, count(*) as instances_susp
                from processinstancelog pi
                where pi.status=4 group by pi.processinstanceid) as suspended
                on (total.pId=suspended.pId)
                left outer join
                (select pi.processinstanceid as pId, count(*) as instances_abrt
                from processinstancelog pi
                where pi.status=3 group by pi.processinstanceid) as aborted
                on (total.pId=aborted.pId)
                where 1 = 1
                order by processname: org.h2.jdbc.JdbcSQLException: Table "PROCESSINSTANCELOG" not found; SQL statement:
select total.processname, ifnull(total.instances,0) total, ifnull(active.instances_act,0) active, ifnull(completed.instances_compl,0) completed, ifnull(pending.instances_pend,0) pending, ifnull(suspended.instances_susp,0) suspended, ifnull(aborted.instances_abrt,0) aborted
                from
                (select pi.processinstanceid as pId, pi.processname as processname, count(*) as instances
                from processinstancelog pi group by pi.processinstanceid,processname) as total
                left outer join
                (select pi.processinstanceid as pId, count(*) as instances_act

**Comment by eschabell** [comment]
With no follow up assuming this has been taken care of, closing for now, feel free to re-open and update if needed.
